version: '3.8'

services:
  app:
    build: .
    container_name: fastapi
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=main
    command: gunicorn -k uvicorn.workers.UvicornWorker --workers 4 -b 0.0.0.0:80 main:app
    env_file:
      - .env  # Archivo de variables de entorno para producción
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
